FROM alpine_3.7-transport-measurability:latest

# netemd is launched in the entrypoint script after network interfaces have
# been configured
COPY entrypoint.bash /root/

# The entrypoint for this container is defined in docker-compose.yml
